SET TIME ZONE 'Asia/Jerusalem';

---
--- 1. שכבת הארגון והתשתית (Chains & Stores)
---

CREATE TABLE IF NOT EXISTS chains (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS data_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id INTEGER REFERENCES chains(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_checksum TEXT UNIQUE,
    source_url TEXT,
    file_type TEXT,
    total_items INTEGER,
    status TEXT DEFAULT 'pending',
    published_at TIMESTAMPTZ,
    scraped_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id INTEGER NOT NULL REFERENCES chains(id) ON DELETE CASCADE,
    store_external_id TEXT,
    name TEXT,
    city TEXT,
    address TEXT,
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    store_type TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

---
--- 2. שכבת הקטגוריות, המותגים והתיוג (שלב 3 - AI Metadata)
---

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    UNIQUE(parent_id, name)
);

CREATE TABLE IF NOT EXISTS brands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    parent_brand_id INTEGER REFERENCES brands(id) ON DELETE SET NULL,
    is_conglomerate BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    brand_id INTEGER REFERENCES brands(id) ON DELETE SET NULL,
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tag_group TEXT
);

CREATE TABLE IF NOT EXISTS product_tags (
    product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
);

CREATE TABLE IF NOT EXISTS product_identifiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    chain_id INTEGER REFERENCES chains(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    external_code TEXT NOT NULL,
    code_type TEXT CHECK (code_type IN ('EAN', 'PLU', 'INTERNAL')),
    UNIQUE (external_code, chain_id)
);

CREATE TABLE IF NOT EXISTS product_specs (
    product_id INTEGER PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    is_weighted BOOLEAN DEFAULT FALSE,
    base_quantity NUMERIC(10,3),
    base_unit TEXT,
    attributes JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

---
--- 3. שכבת המורכבות והמחירים (הנתונים הדינמיים)
---

CREATE TABLE IF NOT EXISTS product_components (
    parent_product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    child_product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (parent_product_id, child_product_id)
);

CREATE TABLE IF NOT EXISTS price_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    store_id INTEGER NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    source_id INTEGER NOT NULL REFERENCES data_sources(id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL,
    --- unit price is the price per base unit
    unit_price NUMERIC(10, 2),
    scraped_at TIMESTAMPTZ DEFAULT NOW(),
    published_at TIMESTAMPTZ,
    raw_xml_item_data JSONB
);

---
--- 4. אינדקסים לביצועים (Scale & Search)
---

CREATE INDEX IF NOT EXISTS idx_price_events_product_id ON price_events(product_id);
CREATE INDEX IF NOT EXISTS idx_price_events_scraped_at ON price_events(scraped_at);
CREATE INDEX IF NOT EXISTS idx_price_events_source_id ON price_events(source_id);
CREATE INDEX IF NOT EXISTS idx_product_identifiers_code ON product_identifiers(external_code);
CREATE INDEX IF NOT EXISTS idx_brands_parent ON brands(parent_brand_id);
CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_stores_location ON stores(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_data_sources_checksum ON data_sources(file_checksum);