"""
Pipeline runner for orchestrating data extraction and upload to MinIO.
"""
import asyncio
import os
from datetime import timedelta
from typing import Dict, List, Optional
import pandas as pd
import requests
from abstractions.scraping_pipeline import ScrapingPipeline


DEFAULT_UPLOAD_BATCH_SIZE = 20


def _chunk_records(records: list, batch_size: int) -> List[list]:
    """Split records into fixed-size batches for uploader requests."""
    return [records[i:i + batch_size] for i in range(0, len(records), batch_size)]


def upload_data_to_uploader(self, records: list, pipeline_name: str, create_bucket: bool) -> None:
    """Upload records to the uploader service. Key is auto-generated by the uploader."""
    pipeline = self.pipelines[pipeline_name]
    pipeline_type = pipeline.pipeline_type()
    uploader_url = os.environ.get("UPLOADER_URL", "http://localhost:8000")
    if pipeline_type == "stores":
        uploader_url = uploader_url + "/upload/stores"
    elif pipeline_type == "prices":
        uploader_url = uploader_url + "/upload/prices"
    
    api_key = os.environ.get("UPLOADER_API_KEY", "dev-key")
    headers = {"Authorization": f"Bearer {api_key}"}
    payload = {"pipeline_name": pipeline_name, "records": records, "create_bucket": create_bucket}

    response = requests.post(uploader_url, json=payload, headers=headers, timeout=120)
    response.raise_for_status()


class PipelineRunner:
    """Handles running pipelines and uploading results to MinIO."""

    def __init__(self, pipelines: Dict[str, ScrapingPipeline]):
        """
        Initialize the pipeline runner with pipelines.
        Args:
            pipelines: Dictionary of pipeline instances keyed by name
        """
        self.pipelines = pipelines

    def run_and_upload(
        self,
        pipeline_name: str,
        time_back: Optional[timedelta] = None,
        max_links: Optional[int] = None,
        create_bucket: bool = True,
        batch_size: int = DEFAULT_UPLOAD_BATCH_SIZE,
    ) -> list:
        """
        Run a specific pipeline and upload results to MinIO.

        Args:
            pipeline_name: Name of the pipeline to run
            time_back: How far back to fetch data (default: 2 hours)
            max_links: Max number of file links to process (optional)
            create_bucket: Whether to create bucket if it doesn't exist
            batch_size: Number of records to send per uploader request

        Returns:
            List of parsed records

        Raises:
            KeyError: If pipeline_name is not found
        """
        if pipeline_name not in self.pipelines:
            raise KeyError(f"Pipeline '{pipeline_name}' not found")
        if batch_size <= 0:
            raise ValueError("batch_size must be greater than 0")

        time_back = time_back or timedelta(hours=2)
        pipeline = self.pipelines[pipeline_name]

        # Extract data
        parsed_records = pipeline.extract(time_back=time_back, max_links=max_links)

        if parsed_records:
            df = pd.DataFrame(parsed_records)

            # Prices are uploaded in grouped batches, while other pipelines are uploaded as a single batch.
            if pipeline.pipeline_type() == "prices":
                grouped_df = df.groupby(["SubChainId", "StoreId", "BikoretNo"], dropna=False)
                upload_batches: List[list] = [group.to_dict("records") for _, group in grouped_df]
            elif pipeline.pipeline_type() == "stores":
                upload_batches = [df.to_dict("records")]
            else:
                raise ValueError(f"Unsupported pipeline type: {pipeline.pipeline_type()}")

            for records in upload_batches:
                for records_chunk in _chunk_records(records, batch_size):
                    upload_data_to_uploader(
                        self,
                        records=records_chunk,
                        pipeline_name=pipeline_name,
                        create_bucket=create_bucket,
                    )

        return parsed_records

    def run_all_and_upload(
        self,
        time_back: Optional[timedelta] = None,
        max_links: Optional[int] = None,
        create_bucket: bool = True,
        batch_size: int = DEFAULT_UPLOAD_BATCH_SIZE,
        max_workers: int = 1,
    ) -> Dict[str, list]:
        """
        Run all pipelines and upload their results to MinIO.

        Args:
            time_back: How far back to fetch data (default: 2 hours)
            max_links: Max number of file links to process per pipeline (optional)
            create_bucket: Whether to create bucket if it doesn't exist
            batch_size: Number of records to send per uploader request
            max_workers: Maximum number of pipelines to run concurrently (default: 1)

        Returns:
            Dictionary mapping pipeline names to their parsed records
        """
        if max_workers == 1:
            # Sequential execution
            results = {}
            for pipeline_name in self.pipelines:
                records = self.run_and_upload(
                    self,
                    pipeline_name=pipeline_name,
                    time_back=time_back,
                    max_links=max_links,
                    create_bucket=create_bucket,
                    batch_size=batch_size,
                )
                results[pipeline_name] = records
            return results
        else:
            # Concurrent execution using asyncio
            return asyncio.run(
                self._run_all_concurrent(
                    time_back=time_back,
                    max_links=max_links,
                    create_bucket=create_bucket,
                    batch_size=batch_size,
                    max_workers=max_workers,
                )
            )

    async def _run_all_concurrent(
        self,
        time_back: Optional[timedelta],
        max_links: Optional[int],
        create_bucket: bool,
        batch_size: int,
        max_workers: int,
    ) -> Dict[str, list]:
        """Internal method for concurrent execution using asyncio."""
        semaphore = asyncio.Semaphore(max_workers)
        
        async def run_with_semaphore(pipeline_name: str):
            async with semaphore:
                return pipeline_name, await asyncio.to_thread(
                    self.run_and_upload,
                    self,
                    pipeline_name=pipeline_name,
                    time_back=time_back,
                    max_links=max_links,
                    create_bucket=create_bucket,
                    batch_size=batch_size,
                )
        
        tasks = [run_with_semaphore(name) for name in self.pipelines]
        results = {}
        
        for coro in asyncio.as_completed(tasks):
            try:
                pipeline_name, records = await coro
                results[pipeline_name] = records
                print(f"Successfully completed: {pipeline_name}")
            except Exception as exc:
                print(f"Error running pipeline: {exc}")
        
        return results

